42 source plugin
Ymbra/migrate_default_content pull request #46
Opened 2017-03-24 18:51 UTC by rvilar

2017-03-25 12:36 UTC, rvilar commented
Now that it works, removed the WIP mark.

2017-03-25 13:40 UTC, rvilar commented
Fixed #42

2017-03-27 19:47 UTC, rodrigoaguilera requested changes

2017-03-27 19:47 UTC, rodrigoaguilera commented on src/Plugin/MigrateDefaultContent/Source/Yaml.php
> + *   id = "Yaml",
No deberia ser esto un nombre máquina como el resto de plugins?

2017-03-28 11:30 UTC, rvilar commented on src/Plugin/MigrateDefaultContent/Source/Yaml.php
> + *   id = "Yaml",
Ya está arreglado quitando la mayúscula.

2017-03-28 11:30 UTC, rodrigoaguilera approved these changes

2017-03-28 11:30 UTC, merged